### ISSUE TITLE
Week 5- Review Ticket ~ Paige McCartin

### ISSUE THREAD

**Issue by paigemccartin** [SlimeyTurtles/jinjaturtles#18]
- [ ] CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. (2 Points - Individual)
     - CB Create Task Coding requirements documented
     - Runtime of Code(with comments) on Replit/Intellij

- [ ] Accounts and Logins Challenges/Hacks ( 3 Points - Pair/Trio)
     - Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
     - Analysis: the csp.nighthawkcodingsociety.com implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.
     - Hack #1 Add Phone Number to Sign Up / Authorization screen
     - Hack #2 Add logout to CRUD screen
     - Hack #3 Add login_required to another portion of the project
     - Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.

**Comment by B-G101** [comment]
Total Score: 3.8/5
Individual 2/2
- CB Create Task completed and documented on GH Pages - Prep to submit to CB on or before May, 2nd. 
     - [X] CB Create Task Coding requirements documented
     - Justification: Create task thoroughly documented on the Github Pages
     - [X] Runtime of Code(with comments) on Replit/Intellij
     - Justification: Code is running and working on IntelliJ 

PBL 1.8/3
- Accounts and Logins Challenges/Hacks 
     - [X] Start or add to existing project:  __init__.py, main.py, requirements.txt and cruddy blueprint directory are things you will need to add to your existing project.  Additionally, you should start with some of the content in templates and static folders.  Find a pair and work on this together.  Ask questions.
     - Justification: Has the templates and crud folders all organized in the IntelliJ
     - [X] Analysis: the csp.nighthawkcodingsociety.com implementation is for educational purposes.  It has some obvious flaws in its security.   Discuss some of the flaws that you see in its security as implemented.
     - Justification: Talked about some of the security issues that are present on the nighthawk coding website
     - [ ] Hack #1 Add Phone Number to Sign Up / Authorization screen
     - [ ] Hack #2 Add logout to CRUD screen
     - [ ] Hack #3 Add login_required to another portion of the project
     - Justification: Doesn't have the hacks completed all the way but made some progress on the and trying to get the code working
     - [ ] Extra Credit:  A quality design would have login and logout on Navbar with user information.   Be sure to have login protecting something on your site, however, do NOT make entire site under login_required.
